# Generated by Django 4.2.7 on 2023-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
